#!/bin/bash
set -e

# Configure PostgreSQL - CENTRAL CONFIGURATION FILE
# 
# This script is the SINGLE SOURCE OF TRUTH for PostgreSQL configuration.
# It builds postgresql.auto.conf incrementally based on:
#   - PG_MODE (primary/replica/standalone)
#   - PGBACKREST_STANZA (enabled/disabled)
#   - Environment variables (performance tuning, etc.)
#
# Called by:
#   - 10-configure-postgres-initdb.sh (for NEW databases via docker-entrypoint-initdb.d/)
#   - entrypoint.sh directly (for EXISTING databases on restart)
#
# Handles all scenarios:
#   - Primary with pgBackRest (archive_mode=on, archive_command, restore_command)
#   - Replica from pg_basebackup (archive_mode=off, primary_conninfo preserved)
#   - Standalone without pgBackRest (minimal config)
#   - Restored from backup (like primary)

# Set default PGDATA if not provided
PGDATA=${PGDATA:-/var/lib/postgresql/18/docker}
export PGDATA

echo "Configuring PostgreSQL..."
echo "Using PGDATA: $PGDATA"
echo "Mode: ${PG_MODE:-primary}"

# Create/update custom configuration file (idempotent)
CUSTOM_CONF="${PGDATA}/postgresql.auto.conf"

# Always start fresh to avoid inheriting wrong settings (especially important for replicas)
# Configuration is always built from environment variables
rm -f ${CUSTOM_CONF}

# Start building configuration file
cat > ${CUSTOM_CONF} <<EOF
# PostgreSQL Auto Configuration
# Generated by configure-postgres.sh
# Mode: ${PG_MODE:-primary}

EOF

# ============================================
# Section 1: Replication Settings (if replica)
# ============================================
if [ "${PG_MODE}" = "replica" ]; then
    echo "Configuring replica-specific settings..."
    
    # Validate required environment variables
    if [ -z "${PRIMARY_HOST}" ]; then
        echo "ERROR: PRIMARY_HOST must be set for replica mode"
        exit 1
    fi
    
    # Generate slot name from hostname (same logic as 03-setup-replica.sh)
    SLOT_NAME=$(hostname | sed 's/-/_/g')
    
    # Build replica configuration from environment variables
    cat >> ${CUSTOM_CONF} <<EOF
# Replica Configuration (streaming from primary)
primary_conninfo = 'host=${PRIMARY_HOST} port=${PRIMARY_PORT:-5432} user=${POSTGRES_USER:-postgres} password=${POSTGRES_PASSWORD} sslmode=require'
primary_slot_name = '${SLOT_NAME}'
hot_standby = on

# Replica-specific: NO archive commands
# Replicas receive WAL via streaming replication from primary
archive_mode = off

EOF
fi

# ============================================
# Section 2: pgBackRest & WAL Archiving (primary/standalone only)
# ============================================
echo "Checking pgBackRest config: PGBACKREST_STANZA='${PGBACKREST_STANZA}', PG_MODE='${PG_MODE}'"
if [ "${PGBACKREST_STANZA}" != "" ] && [ "${PG_MODE}" != "replica" ]; then
    echo "Configuring for pgBackRest with WAL archiving..."
    cat >> ${CUSTOM_CONF} <<EOF
# pgBackRest Configuration
archive_mode = on
archive_command = 'pgbackrest --stanza=${PGBACKREST_STANZA} archive-push %p'
restore_command = 'pgbackrest --stanza=${PGBACKREST_STANZA} archive-get %f "%p"'
archive_timeout = 60

EOF
fi

# ============================================
# Section 3: WAL Configuration (all modes)
# ============================================
cat >> ${CUSTOM_CONF} <<EOF
# WAL Configuration
wal_level = replica
max_wal_senders = ${MAX_WAL_SENDERS:-10}
max_replication_slots = ${MAX_REPLICATION_SLOTS:-10}

EOF

# Always configure SSL
cat >> ${CUSTOM_CONF} <<EOF
# SSL Configuration
ssl = on
ssl_cert_file = '/etc/postgresql/ssl/server.crt'
ssl_key_file = '/etc/postgresql/ssl/server.key'
ssl_ca_file = '/etc/postgresql/ssl/root.crt'

EOF

# Set pg_hba.conf for replication only if not in replica mode
# Both primary and standalone need this for accepting replication connections
if [ "${PG_MODE}" != "replica" ]; then
    # Only add if not already present (idempotent)
    if ! grep -q "# Replication connections - SSL required" ${PGDATA}/pg_hba.conf 2>/dev/null; then
        cat >> ${PGDATA}/pg_hba.conf <<EOF

# Replication connections - SSL required
hostssl replication     all             0.0.0.0/0               scram-sha-256
EOF
    fi
fi

echo "PostgreSQL configuration completed."

# Ensure correct ownership if running as root
if [ "$(id -u)" = "0" ]; then
    chown postgres:postgres ${CUSTOM_CONF}
fi

